### ISSUE TITLE
doc: support for environment variables

### ISSUE THREAD

**Issue by EronWright** [kubernetes-sigs/cli-experimental#66]
The `envs` block that is supported by `configMapGenerator` and `secretGenerator` has undocumented support for OS environment variables, as discussed here:
https://rm3l.org/using-system-envvars-with-kustomize/

Please document the feature.

**Comment by davidboweninrupt** [comment]
@EronWright @rm3l Do you have any thoughts about what we should do with this? It appears to be in limbo which means we can't reasonably use this behaviour even though it's clearly useful for people.

**Comment by afirth** [comment]
It's funny, because the workaround at the end of the [eschewed feature doc](https://kubectl.docs.kubernetes.io/faq/kustomize/eschewedfeatures/#build-time-side-effects-from-cli-args-or-env-variables) is to do some complicated incantation like `echo "FOO=$FOO" > $folder/foo.env && pushd $folder && kustomize edit add configmap foo-configmap --from-file foo.env && popd` which means that not only is it not in version control, the fact that you intend to do it isn't in VC either, but rather buried in some build config. This is exacerbated by the fact that `kustomize edit` [must run in the same directory](https://github.com/kubernetes-sigs/kustomize/issues/2803#issuecomment-774655248) as the kustomize.yaml you're targeting. Mix in calling kustomize with helm, skaffold, or kubectl and this turns into a build program instead of a build step.

So I am a strong **+1** for keeping+documenting this. Perhaps there is appetite to add a check for the footgun of unset variable, perhaps with the option to disable it. That would be easier to do before it's a feature, as the broken users would have an easy fix.

Here's the code, with two comments that it's intentional:
https://github.com/kubernetes-sigs/kustomize/blob/master/api/kv/kv.go#L136
https://github.com/kubernetes-sigs/kustomize/blob/master/api/kv/kv.go#L165
And the [kustomize issue already linked](https://github.com/kubernetes-sigs/kustomize/issues/2497)

Also, @rm3l is not the only one to find it, I've written manifests using it too, so I think removing it is not an option.

**Comment by afirth** [comment]
can I?
/remove-lifecycle rotten

**Comment by afirth** [comment]
AFAIK:
- https://kubectl.docs.kubernetes.io/faq/kustomize/eschewedfeatures/#build-time-side-effects-from-cli-args-or-env-variables should be updated as it is supported
- the section on `.env` files at https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#configmapgenerator could include an example where the value is not set

continued discussion like https://github.com/kubernetes-sigs/kustomize/issues/2301 will be resolved by those updates. I can PR them if there is consensus (@monopole ?)

/remove-lifecycle stale

**Comment by afirth** [comment]
took a stab at fixing this ^
/remove-lifecycle stale
